export const gameData = [
  {
    code: "high-low",
    name: "High-Low Game",
    desc: "Play it now!",
    imageUrl: "/images/games/game-icon.svg",
    url: "game/high-low",
    isDone: true,
  },
  // {
  //   code: "lucky-number",
  //   name: "Lucky Number",
  //   desc: "Play it now!",
  //   imageUrl: "/images/games/ball-icon.svg",
  //   url: "game/lucky-number",
  //   isDone: true,
  // },
  {
    code: "keno",
    name: "Keno",
    desc: "Play it now!",
    imageUrl: "/images/games/ball-icon.svg",
    url: "game/keno",
    isDone: true,
  },
  {
    code: "sport-bet",
    name: "Sport Bet",
    desc: "Play it now!",
    imageUrl: "/images/games/ball-icon.svg",
    url: "/sport",
    isDone: true,
  },
  {
    code: "the-wheel-of-fortune",
    name: "The wheel of fortune",
    desc: "",
    imageUrl: "/images/games/bet-icon2.svg",
    url: "#",
    isDone: false,
  },
  {
    code: "lottery9999",
    name: "Lottery 9999",
    desc: "",
    imageUrl: "/images/games/bet-icon.svg",
    url: "#",
    isDone: false,
  },
  {
    code: "mega-lottery",
    name: "Mega Lottery",
    desc: "",
    imageUrl: "/images/games/ball-icon.svg",
    url: "#",
    isDone: false,
  },
  {
    code: "poker",
    name: "Poker",
    desc: "",
    imageUrl: "/images/games/ball-icon.svg",
    url: "#",
    isDone: false,
  },
  {
    code: "slave-fighting",
    name: "Slave Fighting",
    desc: "",
    imageUrl: "/images/games/ball-icon.svg",
    url: "#",
    isDone: false,
  },
];
